# Generated by Django 4.1.7 on 2023-04-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
